PR: Add templates to pip package
spyder-ide/loghub pull request #68
Opened 2017-03-04 14:44 UTC by goanpeca

Fixes #67

2017-03-04 23:51 UTC, jitseniesen commented on setup.py
> +    package_data={'loghub.templates.content': ['*.txt']},
Why `content` ?

2017-03-05 05:46 UTC, goanpeca commented on setup.py
> +    package_data={'loghub.templates.content': ['*.txt']},
oops!

2017-03-05 21:17 UTC, jitseniesen requested changes
Need to fix directory name

2017-03-05 21:32 UTC, goanpeca commented
@jitseniesen done, I copied the code from another repo and that was a leftover :-). I am finishing a PR to include an improvement on loghub so I can make release 0.3 (which will fix this)

2017-03-06 08:36 UTC, jitseniesen approved these changes

2017-03-07 16:43 UTC, goanpeca commented
@ccordoba12 should I issues 0.2.1 that just fixes this, or go ahead and release 0.3 ?

2017-03-07 19:14 UTC, ccordoba12 commented
Please release 0.2.1 to have a 0.2 working release (because 0.2.0 was broken, if I understand correctly).

Then release 0.3.

2017-03-07 21:11 UTC, merged